### ISSUE TITLE
*2nd Isolated lending protocol

### ISSUE THREAD

**Issue by ControlCplusControlV** [loansharktechteam/Loanshark-Core#1]
Hey just an FYI @loansharktech this is actually the 2nd Isolated lending protocol on Scroll, second to [Cog Finance](https://github.com/CogFinance/Cog-Isolated-Lending) which actually has mainnet deployments already. Thanks, just wanted to let you know. Also be careful forking Rari, its a very difficult codebase and can be very prone to bugs if you're not careful, as its also a Compound V2 fork with a lot of footguns

**Comment by loansharktech** [comment]
Hey @ControlCplusControlV. Appreciate you reaching out and making us aware there are multiple isolated pools protocols building on Scroll. It's great to see others sharing our vision for risk-isolated lending on Scroll. To avoid any confusion on who came first, we'll refer to ourselves simply as a "Risk-Isolated Money Market on Scroll." Right now we aren't forking Rari but building on the battle-tested Compound for our main pool.
